language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - 51101661@qq.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: F6hBkKGa7//TFwPVKjZppGioXwvHLtdS3PA3dCCoiYHOCZIvsRi37DSIHKGvJzCrPci4GM5+tjqzlm3cBOYg2Lgd++/eUtaaHqB5lrZNdfR3pjtp6ysFfs1Zg2ECK/JAyx0sIf3hs+Scky36l0aeimO0mgKqU2blSZSP++O5M5ioyWoooU7eFz1lB0Bi/5PU8j1+RxcGMJPJ2L4KEpD7dO16PsZLUSBIyeE/jRb819mdivXZ6JWS9Yzw30BL1SmsWoqTOYSV9g0Jhi/eB9pQlsp92UJPuRfkCMC7O2rvz3rnFQhxv/l5e3roSlxdF+k9XH3NFHT0QRn7QcT9Q4HblMXqwPgZQFZOh/Ozle5RAeitfnnKvnNsdq9JRbXKICzkjbIGfPfz1K7rjqozq3HZ3ZXJ327zLgfQ2LAN3dIgXXNsBoPFdqs4Uiknon6oMwdrz+Bxo/Hti6v6HkIXAINy28skfbUw+okNc/VwexhrBdsYtBEE1Dezd0ga5nPqAwqA1/5GP3cOuke7RMgKtDApaGik7jZndbwysiTn4lLj6dO3fHUF07JhZSzK5ycF/L/OePE+wo0bXPFK1VLnGLBZ4SlDWePhp4Mm27WHK5WXl+2a0oK80EPBpRhfUzWybC0kwv9phd9V6cKdw36FmYDE4FULJ4fMaFxfo3UrgqQNcfo=
  - secure: De9B7DM+sbpM+3Y4qZvxoHU/fk479pm+pGqX/Y8EMVySGgaZoc4e3ofDiA2oEsfobyhs0VcBYaT1k9gmzSkwEYh5yP8hwbJay99h/9g88zveIgeNmGrF9pY78U/gAho6RSoDrxUSHT2eK/U8fZ3ZvwAA0GNxZRKwBZSxbenu+9YzZR9cvFEvIgidc9/rhZAscf+pju9o72oP4ZYe/XOtuL2465X4EVH5dugT6KucTIUZBA7qD0mauCbw44w6eiSs2Tfdf/4bRyny9Zr240crM8XJnD4+FAf/SPQCTz/VqyqYYzBl8iSAh+qPPfgMdeS4IupYIC1HKJDH1fUHSb7wgv2/uLsFEpMnGxYSjnc35Hlvvxto3PUJeErYE2ga93dEUuwDWD8UGR/pb1VCciKXis7OjsKuKM5sOd1dD9mH5LJuofpa7jtjwUeSdogLsiMnty8jr5Nr+m/n3p/MwhYTG1QqCUljIgJPk/LEC6MDcwa5OIf+4Pba5gsh8FdflniIvSeXWNVDrW6syknBrtxDuhvk4xEFFtvNfT7OlYtS/xgXXvmNYSA9AOmyB+cwGN/8TjBl8lI3zZKevbFqAHPFbG2nVlzKs3RRjNFOb2GM2v/SqZ8X8JmKq0TnmAPZKwYgcZTcLIJQC4Z7BXv0dzN6aX6tOAwLOXiJcvDIgJwQnAM=
  - secure: rX+EalUi8iYtiPtnpjMuQY9pCuv+3rq3rSS/vQdTUhxeQAqugMoFfAsxlBKEpKdmEcyv8g992UiOeW/zju1i67oFmeSotxtA2nhiDky5nU48gJID2G7Fcv2URIi5Lll2mkOYETFVZddiDSYq8m2lmSLgFhTxlMCJkYMLWoBc/5ashk54uJOhSrY6KqKEixDMQ2p5iLaArspGttIV+JrXXBJRrCTitjs158wGvHMO8eVzDqYfl6oh8T1pcpoOSLu+yEh3npgJFpgX56GcmRaCRO7dlQu+OtVfZHik8dFF5N8/rbLsK45Il71T9K09nXV1azrs8yCnZhux39nwSC4yRQoZVFu+mPQDGMmbYTKWUmERo1voV57KHV7zEo0JTj20CZLf6M6HSWivLLgfoYptPjntTf7P1IgHb9UD0R5u3AGMeG/H4lstBmp9fsYRSatJrXuBgLHeSg4RochZ4CaVkLJdifWN1Z5DymfztjTLOLxbBtAfngngvrRfPOK1/TR800oVMpKb9jw6VlrQNNM3NWCaNHnd7xreSmkSPUoSE68mh48ZvsKIGjXrARwlOC7ddJDPwhJlRH70vrAeSM6FsaKMQU0fd1C2ve0S/iGHrKcAvHZkayanFDxnYw19c6ov0Sj/sXuGKObRapPbFHyH/SmdiR8Pw7l58MinQRKLw4Y=
before_install:
- export BUILD_NAME=$TRAVIS_BRANCH-$(date -u "+%Y%m%d")-$TRAVIS_BUILD_NUMBER
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
