language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - 51101661@qq.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: pDLdW2HAg6L7HX5EL/YZwMOzx1my5qwWccr6Fw20EXf9axxIh/MD3Esrn3+OzMxz/qqlMpvP/D9pGyu8wgZ42OvUZZ2PX4Q59FYdN6xWHy+e6NyoqqwA3YJSU7R+odDED7HG2yNtmy9MYNBWK2DNIpPkHnlmEqK7x1azLh8HVF1LRVq2eCqJM8tpUmQekjnZTvj+IEcC6OKyZqvOKi1uCLzeJf9QB5+wud++loJK8Xn8FFeYqMerLXbx16MJydmE+fV7GzxiW4ztF87K8smPrxrn19a+xCh11yn0MuUAFPYRr0mSDbFiVhM3qSIv4s/Gma1K2dFvsfv6c1acsBNauJUZjG2hZYwiwWZXzmHGpcnCTeikFFDNztSoMWmSkx3BGNB80aMpMwAl1NPyFTA6ALyB/9SbL5zpw7JbuAl9IBY4tsZ7+E7vfwZGjw4KSlaCZV0MBAAjFfEQlVCeLBxwi76lGojtfb7YHctL8ZOgSlr1bVyeuqfnDlmhtsFYG0+oPRIGxMnXyKTAUitdxOZGB4HUEPCf4INjP/fNHJBLsEIl1PvIkFpVohyNLghsp+g++aWFLglKx/s5rswcU+XburyQa3hJe98ePkjGKgfkl1ik1lU8LYqdOWkhNobZXACAkFxKBmzyOuf+jZmbXrvBqA+gtw8UwEHY0DIkW6mfYN4=
  - secure: cgHP+/t66ush9t5DxbGfnR3asE3fQ6VFyOBfuMzma9+qb6kbX+UVetowi5THboqA4Lhn7ftrROm1kEkXyeKvd/Q9OPLXW6FMoe2UhOKpjV3AqrQdTTljlJOPAp/3CETaIZ7Vmi2Pq++MZ1zup08+pn06v/Y9Ud4sii3W+5nmL8jh9Fq1eLy57r91ib6yNWCPQP4wZ830QLKDtBsBIpj4397LyB8ZVB7LekThAWsDPBJ/KWE7Oj/OCzXALYSdDuyoutEZDrS96KTzEZbhxidWDgA9FFDimO7sRR7wRrDmeeVfIgHis4e891rsSq+FNNZD5Qb6xevsEn2b3EVpRm1B8uvhqJRN5jk8k9O7dqaarlOX8Zr7Vkydu1v+PGbaBkPEoMr+eH+6T6WU0INPSE/dPb+BSW7l907qXRbU2MEZekjattW0fpTAdYgoiaxJt8QFfP5Ls9fV7o6YzB5PjZ/+yXLj1VGx48Uak4XWA5zLmJLwNdLuSWpl3iNlu/XyRU+55Tz9oCUrNm/e7ZENDHrzDuNu5en7T+l793hmMt6KiNz5bLocRwzoopF576Qm5avIFGzRKxwzQwkt8+PEbqeyMpBhXRcQUsUFvmY5Ddmi2o+yDS5r2rLIYq0FjWsjRkN4vcQOePqJzoEVTjOjDHAHPHZoUbkkFcvQXsnFV1VQMxI=
  - secure: f1rC6Rj8uSCesnlGQr2JU7AYMzULNlmJuyy+6r1apaem2sqMF6t45294cFYl8x7Nu6o8X0wDYD2tkVEpXvEmjrfL2hWnGYnsBdd2T0I2gw7m5xki+kXlTs3cPNpLUqPZqQFt77OXQ6tkW0GF9jwAb9FfRvqKQY7THAAFgAwR/2012AGoaT4XOxV4rU2BbcB8SZNrl2uEoDrWdu6trmca/0wGEXGrqvjwHViRk/CESY5gfKBEWnzjrNCZSXL/JH7ITIo6ug38ypwVe9VdqBN6s4Wcy3/eQ6gr3/nznE8HZyLMDpI/o4Jf/1zlIR5vIiBMrxZ8xNaQCnNJEWeFQVuHcX4yGm89ryOoPr5HOWmJeXgMLMdkvqilKaB4DRnD7jEUEk4IIAYgHZmkGCcLwDPEdxiGuW88k7V9i3klwfx6heulBIYIl+URy45aMXCrqyfCtiqsk8n5uww8WdIvetiZAr9y3jkTLI6/y5xuZummdvbu6GkxjVbpSDFwhybCRAKW1p2++CfSENnciyMZztUHSatxBeHuC8sx2l8922PXmG3Z7M9lpllSXAD5W4Ypvsf1yujo1AlCpSYBN1xEshjdafc1rxWyL6oIcxiACyEGPzksb8RizDdqyG74wvNYSXf/D9RcjFdCBmnIQrxG/d5gwwsKdFyO34fGyzqpxnd/DcM=
before_install:
- export BUILD_NAME=configserver-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
